### ISSUE TITLE
Address browser binary build size

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-core-api#4]
The current browser builds of swagger-core-api are huge and we should investigate if we can fix this.  Here is a useful link: https://gist.github.com/whitlockjc/28b49ddc7558adbea77b  Also, I did some preliminary looking and it seems [json-schema-faker](https://github.com/pateketrueke/json-schema-faker) uses [faker.js](https://github.com/Marak/faker.js) and is including all of its locales, something that should be avoided.

**Comment by theganyo** [comment]
...unless people want it. I wonder if there's a way locales could be plug-n-play?

**Comment by whitlockjc** [comment]
That's the plan.  I know you can require a single local but doing so using json-schema-faker might be interesting.  It will like require some browserify ignores as well.  Not crucial now, just a place holder.
