### ISSUE TITLE
npm module out of date

### ISSUE THREAD

**Issue by TheToolbox** [apigee-127/swagger-core-api#5]
Hey, sorry to bother, but it seems that the npm module is out of date with the library here. It would be quite helpful if we could have those brought together again. Thanks!

**Comment by whitlockjc** [comment]
I don't understand what you mean.  Is there an error or something you're running into?

**Comment by whitlockjc** [comment]
I've figured it out, I see I've neglected to update the `files` section of `package.json`...

**Comment by TheToolbox** [comment]
Sorry I was actually just in the middle of typing a response. Thanks for all your work with Swagger/json schema/etc!






From: Jeremy Whitlock
Sent: ‎Friday‎, ‎July‎ ‎17‎, ‎2015 ‎7‎:‎02‎ ‎PM
To: apigee-127/swagger-core-api
Cc: Jason Oettinger





I've figured it out, I see I've neglected to update the files section of package.json...

**Comment by whitlockjc** [comment]
It's fixed in master.

**Comment by TheToolbox** [comment]
`npm install swagger-core-api --save` still results in the output `swagger-core-api@0.0.01 node_modules/swagger-core-api`, only downloading a skeleton index.js and no dependencies or anything else from this repo. Still seems like npm package isn't linked to the repo. Sorry!

**Comment by whitlockjc** [comment]
Yeah, I haven't produced an NPM build yet.  Until the next NPM release, you can use `npm install https://github.com/apigee-127/swagger-core-api.git --save` and it will work.
