### ISSUE TITLE
Lock down types and attributes

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-core-api#6]
Until we have a way to allow the user to alter object attributes at runtime, we should make it explicitly clear that these created objects are read-only by using `Object.freeze`.

**Comment by mohsen1** [comment]
or `Object.seal` or `Object.freeze` the whole thing?

**Comment by whitlockjc** [comment]
Yeah...I mistakenly created the issue while doing too many things at once.  I want to freeze the object as "freezing" the properties with `Object.defineProperty` only somewhat helps.

**Comment by whitlockjc** [comment]
@mohsen1 @theganyo Do you think this is worth the effort?  I like the idea of immutable objects, especially since changing the internal state directly could cause issues.  But am I really saving anyone from anything?  I mean, to cause a problem you'd have to knowingly do this to yourself.

**Comment by theganyo** [comment]
I'd only do it if you're exposing part or all of the swagger document itself to your clients. (I believe that's the only state that you might be exposing that you rely on, right?)

**Comment by mohsen1** [comment]
Note that `Object.freeze` does not do it recursively so if you want to freeze all methods and stuff in sub-objects you need to go around the whole object recursively yourself and freeze them

**Comment by whitlockjc** [comment]
At this time, I think we should avoid this.  No one is asking for it and I'm not seeing anyone else do this for simple libraries like ours.
