### ISSUE TITLE
Function to get operations by tag

### ISSUE THREAD

**Issue by diogeneshamilton** [apigee-127/swagger-core-api#9]
getOperation is great, but would love a way to grab all operations by tag. I don't have tons of JS experience, but may try to make the PR myself. Would love this functionality though.

**Comment by whitlockjc** [comment]
Let me know if I can help.  If I don't hear from you, or you decide you don't want to do it, I'll gladly do the work.  Prior to your commit, make sure you run `gulp` as that will lint check your code, run Node.js/browser tests, generate browser builds and generate API documentation.  If you want to run those individually:

* `gulp lint`
* `gulp test-node`
* `gulp test-browser`

Docs generation and browser build generation should be done via `gulp`.

**Comment by diogeneshamilton** [comment]
Thanks! I will try it out.

**Comment by whitlockjc** [comment]
Any idea on an ETA?  *(No rush.  I ask only because this is the last issue before I do a release so I'm trying to figure out what kind of timing I'm working with.)*

**Comment by diogeneshamilton** [comment]
No worries- I'm working on it tonight, we shall see how far I get, but hoping to have a PR ready in the next day or so.

**Comment by diogeneshamilton** [comment]
Submitted https://github.com/apigee-127/swagger-core-api/pull/10 let me know if that makes sense!

**Comment by whitlockjc** [comment]
Thanks a lot for your help, excellent PR.
